### ISSUE TITLE
dev-tpsa-new issues

### ISSUE THREAD

**Issue by mattsignorelli** [MethodicalAcceleratorDesign/MAD-NG#431] opened 2024-03-27 20:48 UTC
Running list of issues I find with dev-tpsa-new:
- [x] #432
- [x] `mul` prints a new line to stdout for each call **when only the scalar part is set or is 0 (no 1st, 2nd, 3rd, etc order terms)**
- [x] `div` removes scalar part (e.g. for tpsa a = 1+x and tpsa b = 2,  a/b gives 0.5x)
- [x] #433
- [x] #434 

**With DESC_USE_TMP=0, all my tests with allocated tpsas pass. Making the fix in #434 , all of my tests with DESC_USE_TMP=1 using both the temporaries and allocated tpsas pass**

**Comment by mattsignorelli** [comment] 2024-03-28 13:56
I have updated my comment on `mul` with the more specific finding. Still tracking down the seg fault...

**Comment by ldeniau** [comment] 2024-03-28 14:21
About the seg fault, have you checked the mad_[c]tpsa_nam function? setnam has been replaced by new nam which is doing both.

**Comment by mattsignorelli** [comment] 2024-03-28 14:22
Yes I have checked that. Something seems to be happening silently, because the last two bugs on the checklist only occur sometimes, not every time

**Comment by ldeniau** [comment] 2024-03-28 14:27
One point that has changed in the internal semantic is that lo bound doesn't include non-zero scalar part anymore, because when manipulating high-order specific maps around an orbit, all the intermediate orders were processed while filled with zeros. The drawback of this speedup is that coef[0] must always be treated separately (internally).

**Comment by mattsignorelli** [comment] 2024-03-28 14:31
I see, that makes sense. 

I'm finding the seg fault to appear in `cot`, however this one seems to only occur when I run all tests before it. When only running the lone `cot` test, everything seems okay

**Comment by mattsignorelli** [comment] 2024-03-28 14:32
Here is the specific output:
```
[43550] signal (11.1): Segmentation fault
in expression starting at REPL[1]:1
mad_tpsa_inv at /home/matt/.julia/dev/GTPSA_jll/override/lib/libgtpsa.so (unknown line)
mad_tpsa_div at /home/matt/.julia/dev/GTPSA_jll/override/lib/libgtpsa.so (unknown line)
mad_tpsa_cot at /home/matt/.julia/dev/GTPSA_jll/override/lib/libgtpsa.so (unknown line)
```

**Comment by ldeniau** [comment] 2024-03-28 14:49
mad_tpsa_inv is calling mad_tpsa_scl if v != 1, so before the previous fix, the scalar part was removed.
However, I don't see how this would trigger a seg fault...

**Comment by mattsignorelli** [comment] 2024-03-28 15:32
Getting closer... something about calls to `polar` beforehand is related, other functions may be related too, still investigating

**Comment by ldeniau** [comment] 2024-03-28 15:42
> Getting closer... something about calls to `polar` beforehand is related, other functions may be related too, still investigating

I don't think the problem is coming from a high-level function (mad_tpsa_fun) where I didn't do anything. I suspect more from some corruption of lo, hi or nz beforehand. This is what I observe with DEBUG=2, one of the mul is corrupted during tracking e.g. the LHC.
[...]
-> mad_tpsa_mul:442:
-> mad_tpsa_update:281:
mad_tpsa_update:287: 't' { **lo=64 hi=255** mo=4 uid=0, did=1 nz=00000 ** bug @ o=0 i=-1 }

**Comment by mattsignorelli** [comment] 2024-03-28 16:04
Ok, perhaps it is one of the low level functions that both `polar` and `cot` call. 

If `polar` is called three times with tpsa t = 1+x, I get this:
[75324] signal (11.1): Segmentation fault
in expression starting at REPL[6]:1
mad_tpsa_inv at /home/matt/.julia/dev/GTPSA_jll/override/lib/libgtpsa.so (unknown line)
mad_tpsa_div at /home/matt/.julia/dev/GTPSA_jll/override/lib/libgtpsa.so (unknown line)
mad_tpsa_atan2 at /home/matt/.julia/dev/GTPSA_jll/override/lib/libgtpsa.so (unknown line)
mad_ctpsa_polar at /home/matt/.julia/dev/GTPSA_jll/override/lib/libgtpsa.so (unknown line)

**Comment by ldeniau** [comment] 2024-03-28 16:19
moving to the next debug step, the cdamap used in normal forms after tracking through the HL-LHC gets incorrect input values for minv somehow (with DEBUG=2, no corrupted TPSA is detected):
```
-> mad_ctpsa_minv:112:
error: mad_tpsa_minv.c:118: : invalid rank-deficient map (1st order has zero row)
../mad: 
stack traceback:
	[C]: in function 'mad_ctpsa_minv'
	madl_damap.mad:594: in function '__pow'
	madl_gphys.mad:1322: in function 'normal'
	madl_twiss.mad:413: in function 'twiss_nform'
	madl_twiss.mad:563: in function 'make_mflow'
	madl_twiss.mad:585: in function 'twiss'

```

**Comment by ldeniau** [comment] 2024-03-28 16:30
> Ok, perhaps it is one of the low level functions that both `polar` and `cot` call within inv
> 
> If `polar` is called three times with tpsa t = 1+x, I get this:
> 
> ```
> [75324] signal (11.1): Segmentation fault
> in expression starting at REPL[6]:1
> mad_tpsa_inv at /home/matt/.julia/dev/GTPSA_jll/override/lib/libgtpsa.so (unknown line)
> mad_tpsa_div at /home/matt/.julia/dev/GTPSA_jll/override/lib/libgtpsa.so (unknown line)
> mad_tpsa_atan2 at /home/matt/.julia/dev/GTPSA_jll/override/lib/libgtpsa.so (unknown line)
> mad_ctpsa_polar at /home/matt/.julia/dev/GTPSA_jll/override/lib/libgtpsa.so (unknown line)
> ```
> 
> this is the minimal working example I found. This has to be done with the same tpsa each call

I cannot reproduce the problem, even with 20 calls...
Here is the sequence of calls for a single polar, which works only with ctpsa, not tpsa.

```
> t:print()
-> mad_ctpsa_print:391:

 -UNNAMED-:  C, NV =   6, MO =  1
 ******************************************************************************
     I   COEFFICIENT                                      ORDER   EXPONENTS
     1   1.0000000000000000E+00 +0.0000000000000000E+00i    0     0 0  0 0  0 0
<- mad_ctpsa_print:436:
> MAD.gmath.polar(t,t)
-> mad_ctpsa_polar:139:
-> mad_tpsa_new:191:
-> mad_tpsa_init:169:
<- mad_tpsa_init:172:
<- mad_tpsa_new:197:
-> mad_tpsa_new:191:
-> mad_tpsa_init:169:
<- mad_tpsa_init:172:
<- mad_tpsa_new:197:
-> mad_tpsa_new:191:
-> mad_tpsa_init:169:
<- mad_tpsa_init:172:
<- mad_tpsa_new:197:
-> mad_ctpsa_real:27:
-> mad_tpsa_setval:273:
<- mad_tpsa_setval:275:
<- mad_ctpsa_real:35:
-> mad_ctpsa_imag:50:
-> mad_tpsa_setval:273:
<- mad_tpsa_setval:275:
<- mad_ctpsa_imag:58:
-> mad_tpsa_hypot:786:
-> mad_tpsa_axypbvwpc:878:
-> mad_tpsa_new:191:
-> mad_tpsa_init:169:
<- mad_tpsa_init:172:
<- mad_tpsa_new:197:
-> mad_tpsa_mul:442:
-> mad_tpsa_setval:273:
<- mad_tpsa_setval:275:
<- mad_tpsa_mul:505:
-> mad_tpsa_mul:442:
-> mad_tpsa_setval:273:
<- mad_tpsa_setval:275:
<- mad_tpsa_mul:505:
-> mad_tpsa_axpbypc:822:
-> mad_tpsa_setval:273:
<- mad_tpsa_setval:275:
<- mad_tpsa_axpbypc:830:
-> mad_tpsa_del:203:
<- mad_tpsa_del:205:
<- mad_tpsa_axypbvwpc:886:
-> mad_tpsa_sqrt:212:
-> mad_tpsa_setval:273:
<- mad_tpsa_setval:275:
<- mad_tpsa_sqrt:219:
<- mad_tpsa_hypot:792:
-> mad_tpsa_atan2:592:
-> mad_tpsa_div:511:
-> mad_tpsa_scl:267:
-> mad_tpsa_setval:273:
<- mad_tpsa_setval:275:
<- mad_tpsa_scl:277:
<- mad_tpsa_div:523:
-> mad_tpsa_atan:776:
-> mad_tpsa_setval:273:
<- mad_tpsa_setval:275:
<- mad_tpsa_atan:781:
<- mad_tpsa_atan2:609:
-> mad_ctpsa_cplx:73:
-> mad_ctpsa_setval:273:
<- mad_ctpsa_setval:275:
<- mad_ctpsa_cplx:82:
-> mad_tpsa_del:203:
<- mad_tpsa_del:205:
-> mad_tpsa_del:203:
<- mad_tpsa_del:205:
<- mad_ctpsa_polar:147:
> t:print()
-> mad_ctpsa_print:391:

 -UNNAMED-:  C, NV =   6, MO =  1
 ******************************************************************************
     I   COEFFICIENT                                      ORDER   EXPONENTS
     1   1.0000000000000000E+00 +0.0000000000000000E+00i    0     0 0  0 0  0 0
<- mad_ctpsa_print:436:

```

**Comment by mattsignorelli** [comment] 2024-03-28 17:06
Ok I found one problem: I am compiling with DESC_USE_TMP = 1, and I see that for each call to polar, `ti` in the descriptor is incremented. So one of the temporaries used is not being released atleast with DESC_USE_TMP=1

**Comment by mattsignorelli** [comment] 2024-03-28 18:23
All my tests with allocated tpsas pass with the latest dev-tpsa-new for DESC_USE_TMP = 0

With DEBUG=2 and DESC_USE_TMP = 1, calling `polar` once aborts with the following output:
```
-> mad_ctpsa_polar:139:
-> mad_ctpsa_real:27:
<- mad_ctpsa_real:44:
-> mad_ctpsa_imag:50:
<- mad_ctpsa_imag:67:
-> mad_tpsa_hypot:786:
-> mad_tpsa_axypbvwpc:878:
-> mad_tpsa_mul:442:
-> mad_tpsa_setval:277:
<- mad_tpsa_setval:279:
<- mad_tpsa_mul:505:
-> mad_tpsa_mul:442:
-> mad_tpsa_update:285:
<- mad_tpsa_update:291:
<- mad_tpsa_mul:505:
-> mad_tpsa_axpbypc:822:
<- mad_tpsa_axpbypc:844:
<- mad_tpsa_axypbvwpc:886:
-> mad_tpsa_sqrt:212:
-> mad_tpsa_copy:299:
<- mad_tpsa_copy:316:
-> mad_tpsa_scl:267:
<- mad_tpsa_scl:282:
-> mad_tpsa_mul:442:
-> mad_tpsa_update:285:
<- mad_tpsa_update:291:
<- mad_tpsa_mul:505:
-> mad_tpsa_acc:288:
<- mad_tpsa_acc:311:
-> mad_tpsa_mul:442:
-> mad_tpsa_update:285:
<- mad_tpsa_update:291:
<- mad_tpsa_mul:505:
-> mad_tpsa_acc:288:
<- mad_tpsa_acc:311:
-> mad_tpsa_mul:442:
-> mad_tpsa_update:285:
<- mad_tpsa_update:291:
<- mad_tpsa_mul:505:
-> mad_tpsa_acc:288:
<- mad_tpsa_acc:311:
-> mad_tpsa_mul:442:
-> mad_tpsa_update:285:
<- mad_tpsa_update:291:
<- mad_tpsa_mul:505:
-> mad_tpsa_acc:288:
<- mad_tpsa_acc:311:
<- mad_tpsa_sqrt:233:
<- mad_tpsa_hypot:792:
-> mad_tpsa_atan2:592:
-> mad_tpsa_div:511:
-> mad_tpsa_inv:158:
-> mad_tpsa_copy:299:
<- mad_tpsa_copy:316:
-> mad_tpsa_scl:267:
<- mad_tpsa_scl:282:
-> mad_tpsa_mul:442:
-> mad_tpsa_update:285:
<- mad_tpsa_update:291:
<- mad_tpsa_mul:505:
-> mad_tpsa_acc:288:
<- mad_tpsa_acc:311:
-> mad_tpsa_mul:442:
-> mad_tpsa_update:285:
<- mad_tpsa_update:291:
<- mad_tpsa_mul:505:
-> mad_tpsa_acc:288:
<- mad_tpsa_acc:311:
-> mad_tpsa_mul:442:
-> mad_tpsa_update:285:
<- mad_tpsa_update:291:
<- mad_tpsa_mul:505:
-> mad_tpsa_acc:288:
<- mad_tpsa_acc:311:
-> mad_tpsa_mul:442:
-> mad_tpsa_update:285:
<- mad_tpsa_update:291:
<- mad_tpsa_mul:505:
-> mad_tpsa_acc:288:
<- mad_tpsa_acc:311:
<- mad_tpsa_inv:178:
-> mad_tpsa_mul:442:
-> mad_tpsa_setval:277:
<- mad_tpsa_setval:279:
-> mad_tpsa_copy:299:
<- mad_tpsa_copy:316:
<- mad_tpsa_mul:505:
<- mad_tpsa_div:531:
-> mad_tpsa_atan:776:
-> mad_tpsa_setval:277:
<- mad_tpsa_setval:279:
<- mad_tpsa_atan:781:
<- mad_tpsa_atan2:609:
-> mad_ctpsa_cplx:73:
<- mad_ctpsa_cplx:95:
julia: /home/matt/tpsa/gtpsa/code/mad_tpsa_impl.h:202: mad_tpsa_reltmp: Assertion `d->t[ tid*DESC_MAX_TMP + d->ti[tid]-1 ] == tmp' failed.

[159510] signal (6.-6): Aborted
in expression starting at REPL[5]:1
pthread_kill at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
raise at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
abort at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
unknown function (ip: 0x7f3414c1871a)
__assert_fail at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
mad_tpsa_reltmp at /home/matt/.julia/dev/GTPSA_jll/override/lib/libgtpsa.so (unknown line)
mad_ctpsa_polar at /home/matt/.julia/dev/GTPSA_jll/override/lib/libgtpsa.so (unknown line)
mad_ctpsa_polar! at /home/matt/.julia/dev/GTPSA/src/low_level/ctpsa.jl:556 [inlined]
```

**Comment by mattsignorelli** [comment] 2024-03-28 18:48
Ok I found the problem and submitted a PR. One temporary in polar wasn't being released

All my tests pass now, I do not have tests yet for any of the map methods.

**Comment by ldeniau** [comment] 2024-03-28 20:35
I close this issue for now.

**Closed by ldeniau** 2024-03-28 20:35 UTC
